export const languageOptions = [
    { label: "English", value: "english" },
    { label: "Danish", value: "Danish" },
    { label: "Spanish", value: "Spanish" },
    { label: "French", value: "french" },
    { label: "German", value: "german" },
    { label: "Italian", value: "italian" },
    { label: "Portuguese", value: "portuguese" },
    { label: "Dutch", value: "dutch" },
    { label: "Russian", value: "russian" },
    { label: "Chinese", value: "chinese" },
    { label: "Japanese", value: "japanese" },
    { label: "Korean", value: "korean" },
    { label: "Hindi", value: "hindi" },
    { label: "Bengali", value: "bengali" },
    { label: "Arabic", value: "arabic" },
    { label: "Turkish", value: "turkish" },
    { label: "Hebrew", value: "hebrew" },
    { label: "Swedish", value: "swedish" },
    { label: "Greek", value: "greek" },
  ];

  export const primaryGenreOptions = [
    { label: "Hip-Hop", value: "hip-hop" },
    { label: "Classical", value: "classical" },
    { label: "Electronic", value: "electronic" },
    { label: "Rock", value: "rock" },
    { label: "Jazz", value: "jazz" },
    { label: "Blues", value: "blues" },
    { label: "Reggae", value: "reggae" },
    { label: "Country", value: "country" },
    { label: "Metal", value: "metal" },
    { label: "R&B", value: "rnb" },
    { label: "Soul", value: "soul" },
    { label: "Folk", value: "folk" },
    { label: "Funk", value: "funk" },
    { label: "Gospel", value: "gospel" },
    { label: "Punk", value: "punk" },
    { label: "Latin", value: "latin" },
    { label: "K-Pop", value: "k-pop" },
    { label: "Afrobeat", value: "afrobeat" },
  ];

  export const secondaryGenreOptions = [
    { label: "Blues", value: "blues" },
    { label: "Funk", value: "funk" },
    { label: "Reggae", value: "reggae" },
    { label: "Jazz", value: "jazz" },
    { label: "Soul", value: "soul" },
    { label: "Country", value: "country" },
    { label: "Latin", value: "latin" },
    { label: "Folk", value: "folk" },
    { label: "R&B", value: "rnb" },
    { label: "Gospel", value: "gospel" },
    { label: "Electronic", value: "electronic" },
    { label: "Synthwave", value: "synthwave" },
    { label: "Disco", value: "disco" },
    { label: "K-Pop", value: "k-pop" },
    { label: "J-Pop", value: "j-pop" },
    { label: "Afrobeat", value: "afrobeat" },
    { label: "Dancehall", value: "dancehall" },
    { label: "Bhangra", value: "bhangra" },
    { label: "Ska", value: "ska" },
    { label: "Punk", value: "punk" },
  ];

  export const rolesOptions = [
    { label: "Main Artist", value: "main_artist" },
    { label: "Featured Artist", value: "featured_artist" },
    { label: "Producer", value: "producer" },
    { label: "Songwriter", value: "songwriter" },
    { label: "Composer", value: "composer" },
    { label: "Vocalist", value: "vocalist" },
    { label: "Background Vocalist", value: "background_vocalist" },
    { label: "Lyricist", value: "lyricist" },
    { label: "Instrumentalist", value: "instrumentalist" },
    { label: "Arranger", value: "arranger" },
    { label: "Mixing Engineer", value: "mixing_engineer" },
    { label: "Mastering Engineer", value: "mastering_engineer" },
    { label: "DJ", value: "dj" },
    { label: "Sound Designer", value: "sound_designer" },
    { label: "Music Director", value: "music_director" },
  ];
  